version: '3'

services:
  app:
    tty: true
    build:
      context: .
      target: build
    command: npm run dev
    volumes:
      - './:/app'
    ports:
      - '8080:8080'
      - '9229:9229'
    env_file:
      - '.env'

  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'