version: '3.7'

services:
  app:
    tty: true
    build:
      context: .
      target: build
    # stop_signal: SIGINT
    entrypoint: ./docker-entrypoint.sh
    command: npm run dev
    volumes:
      - './:/app'
    ports:
      - '8080:8080'
      - '9229:9229'
    depends_on:
      - 'db'
      - 'redis'
    env_file:
      - '.env'

  db:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      # Contains DB username and password
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'