name: Create Staging Deployment

on:
  push:
    branches:
      - main

jobs:
  create-deployment:
    runs-on: ubuntu-latest

    steps:
      -
        id: create-deployment
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
              auto_merge: false,
              required_contexts: [],
              environment: 'staging',
              payload: {
                test: 'test payload data'
              },
              description: 'Test deployment description'
            })