name: Tag Release

on:
  push:
    branches:
      - main

jobs:
  tag-release:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tag Release
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"

          RELEASE_NAME=$(git show -s --date=format:'%Y%m%d' --format=%cd-%h ${{ github.sha }})

          git tag \
            -a $RELEASE_NAME \
            -m "$(git show --pretty=medium -s)"

          git push origin $RELEASE_NAME